apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: otel-collector-production
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: production
  source:
    repoURL: https://github.com/tracefox-ai/tfx-gitops.git
    targetRevision: HEAD
    path: helm/otel-collector
    helm:
      valueFiles:
        - values-production.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
